<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>Home on ୧ʕ •ᴥ•ʔ୨ Silent Lake</title><link>https://pagliacii.github.io/silent-lake/</link><description>Recent content in Home on ୧ʕ •ᴥ•ʔ୨ Silent Lake</description><generator>Hugo -- gohugo.io</generator><language>zh-CN</language><copyright>Jason Huang © 2023</copyright><atom:link href="https://pagliacii.github.io/silent-lake/index.xml" rel="self" type="application/rss+xml"/><item><title>Python 列表推导式里变量未定义的问题</title><link>https://pagliacii.github.io/silent-lake/blog/a-python-list-comprehensions-scope-problem/</link><pubDate>Sun, 15 Oct 2023 23:29:26 +0800</pubDate><guid>https://pagliacii.github.io/silent-lake/blog/a-python-list-comprehensions-scope-problem/</guid><description>&lt;p>之前在&lt;a href="https://pythonhunter.org/">捕蛇者说&lt;/a>的听众群里有人问了下面这个问题：&lt;/p>
&lt;blockquote>
&lt;p>为什么 &lt;code>eval('''exec(&amp;quot;d={};[d for i in range(1)]&amp;quot;)''',{},{})&lt;/code> 会报错 NameError
而 &lt;code>eval('''exec(&amp;quot;d={};[d for i in range(1)]&amp;quot;,None,{})''')&lt;/code> 和 &lt;code>eval('''exec(&amp;quot;d={};[d]&amp;quot;,None,{})''')&lt;/code> 都不会报错？&lt;/p>
&lt;/blockquote>
&lt;p>挺有趣的，为什么在有 &lt;code>d={}&lt;/code> 的情况下还会出现 &lt;code>NameError&lt;/code> 呢？下面就来分析看看。&lt;/p></description></item></channel></rss>